### ISSUE TITLE
error C2766: explicit specialization; 'std::hash<QString>' has already been defined

### ISSUE THREAD

**Issue by haik** [BTIRAI/pacman#1]
When I build the project with Visual Studio 2019, I encounter the following error:
~\pacman\bt_editor\qt_nodeditor\src\QStringStdHash.hpp(16): **error C2766: explicit specialization;** 'std::hash<QString>' has already been defined.
I was wondering if anyone can help me solve the problem?

**Comment by miccol** [comment]
give me a couple of days to look into that problem. 
Thanks

**Comment by miccol** [comment]
Looks like it is a problem in qt_nodeditor, please file the issue in their repository.
https://github.com/paceholder/nodeeditor

Thanks for reporting

**Comment by haik** [comment]
OK, thanks for your help.
