### ISSUE TITLE
Exception: The agent BTAgent is not specified in any *Agents.py.

### ISSUE THREAD

**Issue by ZhaoLv** [BTIRAI/pacman#2]
When I select the file pacmantree.xml and press the Play icon, the pacman game cannot be called, and the following error is reported:
Setting mode: 1
<module 'ghostAgents' from '/home/zhaolv/pacman-master/build/ghostAgents.py'>
<module 'keyboardAgents' from '/home/zhaolv/pacman-master/build/keyboardAgents.py'>
Cannot Import  PacmanAgents.py
<module 'searchAgents' from '/home/zhaolv/pacman-master/build/searchAgents.py'>
Traceback (most recent call last):
  File "pacman.py", line 866, in <module>
    args = readCommand( sys.argv[1:] ) # Get game components based on input
  File "pacman.py", line 582, in readCommand
    pacmanType = loadAgent(options.pacman, noKeyboard)
  File "pacman.py", line 659, in loadAgent
    raise Exception('The agent ' + pacman + ' is not specified in any *Agents.py.')
Exception: The agent BTAgent is not specified in any *Agents.py.

I was wondering if anyone can help me solve the problem?

**Comment by miccol** [comment]
Can you give me the detail of your machine? (OS version and python version installed)

**Comment by sebihoefle** [comment]
I had the same problem on MacOS. Debugging showed me that TK was not configured:
```import _tkinter # If this fails your Python may not be configured for Tk```
Solved by running `brew install python-tk`.

**Comment by miccol** [comment]
Thanks @sebihoefle
