### ISSUE TITLE
the tutorial is too old,look at this.

### ISSUE THREAD

**Issue by ZhangQuan-hub** [BTIRAI/pacman#3]
Run in a terminal the following commands:

cd bt_editor

./behavior_tree_editor

but i got this:

behavior_tree_editor_autogen in the bt_editor folder,it is a folder ,too,not a file can be execute.

**Comment by TomLim210** [comment]
Hi, not sure if it is still relevant for you but maybe other people run into the same issue. 
The file is one directory up in the /build directory. So after the 'make' command just skip the 'cd bt_editor' and execute the file with './behavior_tree_editor'

**Comment by miccol** [comment]
Somehow I did not get the notification for this. #7 fixes it
