### ISSUE TITLE
Compiling the code in ubuntu 22.04

### ISSUE THREAD

**Issue by antbono** [BTIRAI/pacman#4]
Hi everyone!

I tried to build the code in ubuntu 22.04 but there is the following problem with the qt_node_editor

![Screenshot from 2023-04-18 18-33-54](https://user-images.githubusercontent.com/7023471/232844552-5692a471-f2ec-4ded-aeac-db2fe0f8f1b1.png)

Has anyone had the same issue? Thanks!

Just to add info here there is the cmake output
![Screenshot from 2023-04-18 18-38-10](https://user-images.githubusercontent.com/7023471/232845671-6d44abcf-5545-476f-aba8-da3b7c897255.png)

**Comment by ciaran-helgen** [comment]
There appears to be an issue with the QT5 version packaged with Ubuntu 22.04. A workaround is to simply comment out the lines which redefine the QString variable. It is located in pacman/bt_editor/qt_nodeditor/src/QStringStdHash.hpp. My understanding is that QString is already defined by QT5 in the later versions, so redefining is here leads to the build error you saw.
```
#pragma once

#include <QtCore/QString>
#include <QtCore/QVariant>

namespace std
{
// template<>
// struct hash<QString>
// {
//   inline std::size_t
//   operator()(QString const &s) const
//   {
//     return qHash(s);
//   }
// };
}
```
I should also add that I have encountered other issues with the code on 22.04 which prevent it from working. There is some issue with the agent modules failing to import, and I believe the method of concatenating the dict_keys is not compatible with newer versions of Python3.
It works fine on Ubuntu 20.04 however (Python 2.7.18, QT5 5.12.8).
I tried to quickly patch some things but it's still not in a working state. I'll open a PR if I get it working (including a method of checking the QT5 version)

**Comment by miccol** [comment]
Somehow I did not get the notification for this. #7 fixes it
